#FROM node:20-bookworm AS base
#RUN apt-get install -y curl && corepack enable
FROM node:alpine AS base
RUN apk --no-cache add curl && corepack enable

FROM base AS builder

ARG NODE_ENV
ARG ESL_HOST
ARG ESL_PORT
ARG ESL_PASSWORD
ARG KEYCLOAK_CLIENT_ID
ARG KEYCLOAK_CLIENT_SECRET
ARG PUBLIC_KEYCLOAK_CLIENT_ID
ARG PUBLIC_KEYCLOAK_REALM
ARG PUBLIC_KEYCLOAK_URL
ARG CI_ENVIRONMENT_NAME

ENV NUXT_ESL_HOST=${ESL_HOST}
ENV NUXT_ESL_PORT=${ESL_PORT}
ENV NUXT_ESL_PASSWORD=${ESL_PASSWORD}
ENV NUXT_KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID}
ENV NUXT_KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}
ENV NUXT_PUBLIC_KEYCLOAK_CLIENT_ID=${PUBLIC_KEYCLOAK_CLIENT_ID}
ENV NUXT_PUBLIC_KEYCLOAK_REALM=${PUBLIC_KEYCLOAK_REALM}
ENV NUXT_PUBLIC_KEYCLOAK_URL=${PUBLIC_KEYCLOAK_URL}
ENV CI_ENVIRONMENT_NAME=${CI_ENVIRONMENT_NAME}

WORKDIR /app
COPY . .
RUN pnpm install && pnpm build


FROM base AS runtime

ARG NODE_ENV

COPY --from=builder /app/.output /app/.output
WORKDIR /app

ENTRYPOINT ["node", ".output/server/index.mjs"]